# Generated by Django 4.0.8 on 2024-03-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0025_enrollment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='gpt_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
