# Generated by Django 4.0.8 on 2024-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0026_solution_gpt_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='gpt_feedback_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback_files/'),
        ),
    ]
